default l0
menu title Megrez operating system
prompt 1
timeout 100

label l0
	menu label RockOS GNU/Linux 6.6.87-win2030
	linux /vmlinuz-6.6.87-win2030
	initrd /initrd.img-6.6.87-win2030
	fdtdir /dtbs/linux-image-6.6.87-win2030/
	
	append root=PARTUUID=b0f77ad6-36cd-4a99-a8c0-31d73649aa09 console=ttyS0,115200 root=PARTUUID=b0f77ad6-36cd-4a99-a8c0-31d73649aa09 rootfstype=ext4 rootwait rw earlycon selinux=0 LANG=en_US.UTF-8

label asterinas-basic
menu label Asterinas Basic
linux /asterinas-6694c4c7ff5a.booti
initrd /stage1-d62ab8325e03.cpio
fdt /megrez-465cb129333c.dtb
append console=ttyS0 loglevel=info asterinas.klog_capture=info init=/init -- --root-init=basic

label asterinas-probe
menu label Asterinas Probe
linux /asterinas-6694c4c7ff5a.booti
initrd /stage1-d62ab8325e03.cpio
fdt /megrez-465cb129333c.dtb
append console=ttyS0 loglevel=info asterinas.klog_capture=info init=/init asterinas.reboot_after=90 -- --root-init=probe-auto

label asterinas-desktop
menu label Asterinas Desktop
linux /asterinas-6694c4c7ff5a.booti
initrd /stage1-ea446515661f.cpio
fdt /megrez-465cb129333c.dtb
append console=tty0 loglevel=off asterinas.klog_capture=info init=/init asterinas.mmc_write_partition2 systemd.mask=asterinas-desktop-m5-network.service systemd.mask=serial-getty@ttyS0.service systemd.mask=console-getty.service systemd.setenv=ASTERINAS_BROWSER_WEB_BASIC_ONLY=1 systemd.setenv=ASTERINAS_WEB_NETWORK_MODE=proxy systemd.setenv=ASTERINAS_DESKTOP_PROXY_URL=http://10.100.19.216:17893 systemd.setenv=ASTERINAS_DESKTOP_PROXY_HOST=10.100.19.216 systemd.setenv=ASTERINAS_DESKTOP_PROXY_PORT=17893 systemd.setenv=ASTERINAS_DESKTOP_FIXTURE_URL=http://10.100.19.216:17894/asterinas-network-probe.bin systemd.setenv=ASTERINAS_DESKTOP_FIXTURE_SIZE=65536 systemd.setenv=ASTERINAS_DESKTOP_FIXTURE_SHA256=7daca2095d0438260fa849183dfc67faa459fdf4936e1bc91eec6b281b27e4c2 systemd.setenv=ASTERINAS_DESKTOP_FIXTURE_REQUESTS=20 asterinas.net=eic7700-rj45,10.100.19.200/21,10.100.16.1 asterinas.neighbor=eic7700-rj45,10.100.16.1,4c:d6:29:18:93:43 asterinas.neighbor=eic7700-rj45,10.100.19.216,04:7c:16:47:50:4e -- --root-init=systemd --debug-console=isolated-root

