# SPDX-License-Identifier: MPL-2.0

import copy
import hashlib
import json
import os
import shutil
from pathlib import Path
import subprocess
import sys
import tempfile
import unittest
from unittest.mock import Mock, patch

from tools.riscv import megrez_boot_menu as menu
from tools.riscv import megrez_menu_board as board
from tools.riscv import megrez_menu_qemu as qemu
from tools.riscv.debian.rootfs import stage1_basic


VENDOR = """# generated by u-boot-update
default l0
menu title U-Boot menu
prompt 2
timeout 50
label l0
\tmenu label RockOS normal
\tlinux /vmlinuz-6.6
\tinitrd /initrd.img-6.6
\tfdtdir /dtbs/linux-6.6/
\tappend root=PARTUUID=1234 console=ttyS0,115200 rw

label l0r
\tmenu label rescue
\tlinux /vmlinuz-6.6
"""


def document():
    value = {
        "schema_version": 3,
        "vendor": VENDOR,
        "artifacts": {},
        "desktop_args": menu.BASE_ARGS + " -- --root-init=systemd",
    }
    for name in menu.ARTIFACTS:
        payload = name.encode()
        sha = hashlib.sha256(payload).hexdigest()
        value["artifacts"][name] = menu.identity(payload, f"/{name}-{sha[:12]}.bin")
    value["extlinux"] = menu.render(value)
    return value


class BootMenuTests(unittest.TestCase):
    @unittest.skipUnless(
        shutil.which("dtc") and shutil.which("fdtput") and shutil.which("fdtget"),
        "device-tree tools are required",
    )
    def test_prepared_dtb_preserves_source_and_encodes_existing_handoff(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            source, output = root / "source.dtb", root / "prepared.dtb"
            subprocess.run(
                ["dtc", "-I", "dts", "-O", "dtb", "-o", str(source)],
                input="/dts-v1/; / { #address-cells = <2>; #size-cells = <2>; chosen {}; };",
                text=True,
                check=True,
                capture_output=True,
            )
            original = source.read_bytes()
            menu.prepare_dtb(source, output)
            self.assertEqual(source.read_bytes(), original)
            registers = subprocess.check_output(
                [
                    "fdtget",
                    "-t",
                    "x",
                    str(output),
                    menu.MEGREZ_FRAMEBUFFER.node_path,
                    "reg",
                ],
                text=True,
            ).split()
            self.assertEqual(
                [int(value, 16) for value in registers],
                [0, menu.MEGREZ_FRAMEBUFFER.address, 0, menu.MEGREZ_FRAMEBUFFER.size],
            )
            usb = subprocess.check_output(
                ["fdtget", "-t", "s", str(output), "/chosen", "asterinas,usb-host"],
                text=True,
            ).split()
            self.assertEqual(
                usb,
                [
                    "/soc/usb0@50480000/dwc3@50480000",
                    "/soc/usb1@50490000/dwc3@50490000",
                ],
            )
            link = root / "link.dtb"
            link.symlink_to(root / "absent.dtb")
            with self.assertRaises(menu.BootManifestError):
                menu.prepare_dtb(source, link)
            self.assertFalse((root / "absent.dtb").exists())

    def test_qemu_launch_failure_closes_both_terminal_descriptors(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            payload = root / "image"
            payload.write_bytes(b"fixture")
            descriptors = os.openpty()
            with (
                patch.object(qemu.os, "openpty", return_value=descriptors),
                patch.object(qemu.subprocess, "Popen", side_effect=FileNotFoundError),
            ):
                with self.assertRaises(FileNotFoundError):
                    qemu.run(payload, payload, "basic", root / "result")
            for descriptor in descriptors:
                with self.assertRaises(OSError):
                    os.fstat(descriptor)

    def test_busybox_installs_cached_static_binary_and_rejects_wrong_arch(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            source = root / "busybox"
            source.write_bytes(b"#!/bin/sh\n")
            with self.assertRaisesRegex(ValueError, "RISC-V ELF64"):
                stage1_basic.install_busybox(root / "stage", source)
            source.write_bytes(b"\x7fELF\x02\x01" + bytes(12) + b"\xf3\x00")
            with patch.object(stage1_basic.subprocess, "check_output", return_value=""):
                stage1_basic.install_busybox(root / "stage", source)
            self.assertEqual(
                (root / "stage/bin/busybox").read_bytes(), source.read_bytes()
            )
            self.assertEqual((root / "stage/bin/sh").readlink(), Path("busybox"))

    def test_desktop_checks_use_short_acknowledged_commands(self):
        session = Mock()
        responses = [
            "\nDISPLAY_RC=0\r\nroot@asterinas-debug:/#",
            "\nFIREFOX_RC=0\r\nroot@asterinas-debug:/#",
            "\nWINDOW_RC=0\r\nroot@asterinas-debug:/#",
        ]
        with patch.object(board, "query_guest", side_effect=responses) as query:
            self.assertTrue(board.desktop_ready(session))
            for call in query.call_args_list:
                self.assertLessEqual(len(call.args[1]), 96)
        session.command.assert_not_called()
        with (
            patch.object(board, "query_guest", return_value="bash: syntax error\n"),
            self.assertRaisesRegex(menu.BootManifestError, "truncated"),
        ):
            board.desktop_ready(session)

    def test_guest_query_reuses_full_duplex_transport_with_one_safe_retry(self):
        session, serial = Mock(), Mock()
        serial.checkpoint.return_value = 0
        serial.transcript = b"QUERY_OK\nroot@asterinas-debug:/#"
        serial.wait_for.side_effect = [TimeoutError(), None, None]
        with patch.object(board, "SerialConsole", return_value=serial) as constructor:
            self.assertIn("QUERY_OK", board.query_guest(session, "echo QUERY_OK"))
            constructor.assert_called_once_with(
                session.fd, max_bytes=1024 * 1024, tx_delay=0.005
            )
        self.assertEqual(
            [call.args[0] for call in serial.send.call_args_list],
            [b"echo QUERY_OK\n", b"\x03\n", b"echo QUERY_OK\n"],
        )
        serial.wait_for.side_effect = [TimeoutError(), None, TimeoutError()]
        with (
            patch.object(board, "SerialConsole", return_value=serial),
            self.assertRaises(TimeoutError),
        ):
            board.query_guest(session, "echo QUERY_OK")

    def test_preserves_selected_vendor_stanza(self):
        label, stanza, fields = menu.vendor_default(VENDOR)
        self.assertEqual(label, "l0")
        self.assertEqual(
            stanza, VENDOR[VENDOR.index("label l0\n") : VENDOR.index("label l0r\n")]
        )
        self.assertEqual(fields["fdtdir"], "/dtbs/linux-6.6/")

    def test_fallback_selects_vendor_default_after_reordered_rescue_entry(self):
        value = document()
        header, stanzas = VENDOR.split("label l0\n", 1)
        normal, rescue = stanzas.split("label l0r\n", 1)
        value["vendor"] = header + "label l0r\n" + rescue + "label l0\n" + normal
        value["extlinux"] = menu.render(value)
        operations = Mock()
        session = operations._require_session.return_value
        with patch.object(board.os, "write"):
            board.boot_cycle(
                operations, value, "fallback", "debian", "fixture", "0" * 32
            )
        self.assertEqual(session.send.call_args_list[1].args, ("2",))
        operations.reboot_and_recover.assert_called_once_with("fixture", 120)

    def test_rejects_missing_duplicate_or_inherited_defaults(self):
        variants = (
            VENDOR.replace("default l0\n", ""),
            VENDOR.replace("default l0\n", "default absent\n"),
            "default l0\n" + VENDOR,
            VENDOR + "label l0\n",
            "append inherited=1\n" + VENDOR,
            VENDOR.replace("\tfdtdir", "\tfdt /file.dtb\n\tfdtdir"),
            VENDOR.replace("/vmlinuz-6.6", "/../kernel"),
        )
        for value in variants:
            with self.subTest(value=value), self.assertRaises(menu.BootManifestError):
                menu.vendor_default(value)

    def test_four_modes_share_kernel_and_dtb(self):
        value = document()
        menu.validate(value)
        text = value["extlinux"]
        self.assertTrue(text.startswith("default l0\n"))
        self.assertIn("timeout 100\n", text)
        self.assertEqual(text.count("\nlabel "), 4)
        self.assertEqual(text.count(value["artifacts"]["kernel"]["path"]), 3)
        self.assertEqual(text.count(value["artifacts"]["dtb"]["path"]), 3)
        self.assertEqual(text.count(value["artifacts"]["stage1"]["path"]), 2)
        self.assertEqual(text.count("asterinas.reboot_after="), 1)
        self.assertIn("--root-init=basic", text)
        self.assertIn("--root-init=probe-auto", text)

    def test_rejects_identity_and_argument_drift(self):
        for change in (
            lambda d: d.update(schema_version=2),
            lambda d: d.update(
                extlinux=d["extlinux"].replace("timeout 100", "timeout 0")
            ),
            lambda d: d["artifacts"]["stage1"].update(path="/stage1-current.cpio"),
            lambda d: d["artifacts"]["kernel"].update(size=True),
            lambda d: d["artifacts"]["dtb"].update(crc32="invalid"),
            lambda d: d.update(
                desktop_args=menu.BASE_ARGS
                + " asterinas.reboot_after=90 -- --root-init=systemd"
            ),
            lambda d: d.update(desktop_args=menu.BASE_ARGS + " -- --root-init=basic"),
        ):
            value = document()
            change(value)
            with self.assertRaises(menu.BootManifestError):
                menu.validate(value)

    def test_shared_desktop_stage1_needs_no_extra_copy(self):
        value = document()
        value["artifacts"]["desktop_stage1"] = copy.deepcopy(
            value["artifacts"]["stage1"]
        )
        value["extlinux"] = menu.render(value)
        menu.validate(value)
        script = menu.publication_script(value, "http://192.168.1.1:8000")
        self.assertEqual(script.count("install -D -m 0444"), 3)

    def test_rejects_isolated_console_as_a_desktop_entry(self):
        value = document()
        value["desktop_args"] = (
            menu.BASE_ARGS + " -- --root-init=systemd --debug-console=isolated-root"
        )
        value["extlinux"] = menu.render(value)
        with self.assertRaisesRegex(menu.BootManifestError, "root-init"):
            menu.validate(value)

    def test_publication_is_config_last_and_only_publishes_canary(self):
        value = document()
        script = menu.publication_script(value, "http://192.168.1.1:8000")
        result = subprocess.run(
            ["sh", "-n"], input=script, text=True, capture_output=True
        )
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertNotIn("/boot/extlinux/asterinas.conf", script)
        self.assertNotIn("saveenv", script)
        self.assertNotIn("mmcblk1p2", script)
        self.assertLess(script.index("if test -e /boot/"), script.index("curl -fSs"))
        self.assertGreater(script.index("mv -f"), script.rindex("install -D"))

    def test_prepare_verifies_before_writing_selector(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            vendor = root / "vendor.conf"
            vendor.write_text(VENDOR)
            sources = {}
            for name in menu.ARTIFACTS:
                sources[name] = root / name
                sources[name].write_bytes(name.encode())
            value = menu.prepare(
                vendor, sources, document()["desktop_args"], root / "out"
            )
            self.assertEqual(
                (root / "out/asterinas-menu.conf").read_text(), value["extlinux"]
            )
            for item in value["artifacts"].values():
                self.assertEqual(
                    hashlib.sha256(
                        (root / "out" / item["path"][1:]).read_bytes()
                    ).hexdigest(),
                    item["sha256"],
                )
            result = subprocess.run(
                [
                    sys.executable,
                    "-m",
                    "tools.riscv.megrez_boot_menu",
                    "prepare",
                    "--vendor",
                    str(vendor),
                    "--kernel",
                    str(sources["kernel"]),
                    "--stage1",
                    str(sources["stage1"]),
                    "--dtb",
                    str(sources["dtb"]),
                    "--desktop-args",
                    document()["desktop_args"],
                    "--output",
                    str(root / "cli"),
                ],
                capture_output=True,
                text=True,
            )
            self.assertEqual(result.returncode, 0, result.stderr)
            shared = json.loads((root / "cli/manifest.json").read_text())
            self.assertEqual(
                shared["artifacts"]["stage1"], shared["artifacts"]["desktop_stage1"]
            )

    def test_corrupt_installed_artifact_stops_before_any_download(self):
        value = document()
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            boot = root / "boot"
            (boot / "extlinux").mkdir(parents=True)
            (boot / "extlinux/extlinux.conf").write_text(VENDOR)
            active = boot / "extlinux/asterinas.conf"
            active.write_text("previous working selector")
            item = value["artifacts"]["kernel"]
            (boot / item["path"][1:]).write_bytes(b"corrupt")
            script = menu.publication_script(value, "http://192.168.1.1:8000")
            script = script.replace("/boot", str(boot))
            script = script.replace(
                "set -eu",
                "set -eu\nfindmnt() { echo /dev/mmcblk1p1; }\ncurl() { echo DOWNLOAD_ATTEMPT; return 99; }",
            )
            result = subprocess.run(
                ["sh"], input=script, text=True, capture_output=True
            )
            self.assertNotEqual(result.returncode, 0)
            self.assertNotIn("DOWNLOAD_ATTEMPT", result.stdout)
            self.assertEqual(active.read_text(), "previous working selector")
            self.assertEqual(list((boot / "extlinux").glob("asterinas-menu-*")), [])

    def test_promotion_requires_distinct_complete_physical_evidence(self):
        value = document()
        sha = hashlib.sha256(value["extlinux"].encode()).hexdigest()
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            with self.assertRaisesRegex(
                menu.BootManifestError, "qualification incomplete"
            ):
                menu.promotion_script(value, root)
            index = 0
            for mode, count in (
                ("rockos", 3),
                ("fallback", 3),
                ("basic", 3),
                ("probe", 3),
                ("desktop", 2),
            ):
                for _ in range(count):
                    index += 1
                    run = root / str(index)
                    run.mkdir()
                    log = f"run {index}\nOpenSBI\nU-Boot \n".encode()
                    (run / "serial.log").write_bytes(log)
                    result = {
                        "action": "cycle",
                        "mode": mode,
                        "run_id": f"{index:032x}",
                        "passed": True,
                        "recovered": True,
                        "menu_sha256": sha,
                        "serial_sha256": hashlib.sha256(log).hexdigest(),
                    }
                    (run / "result.json").write_text(json.dumps(result))
            script = menu.promotion_script(value, root)
            checked = subprocess.run(
                ["sh", "-n"], input=script, text=True, capture_output=True
            )
            self.assertEqual(checked.returncode, 0, checked.stderr)
            self.assertIn("asterinas-backup-", script)
            for item in value["artifacts"].values():
                self.assertLess(
                    script.index(item["sha256"]), script.index("temporary=$(mktemp")
                )
            boot = root / "boot"
            (boot / "extlinux").mkdir(parents=True)
            (boot / "extlinux/extlinux.conf").write_text(VENDOR)
            (boot / f"extlinux/asterinas-menu-{sha[:12]}.conf").write_text(
                value["extlinux"]
            )
            active = boot / "extlinux/asterinas.conf"
            active.write_text("previous working selector")
            for name, item in value["artifacts"].items():
                (boot / item["path"][1:]).write_bytes(name.encode())
            corrupt = boot / value["artifacts"]["dtb"]["path"][1:]
            corrupt.write_bytes(b"bad")
            runnable = script.replace("/boot", str(boot)).replace(
                "set -eu", "set -eu\nfindmnt() { echo /dev/mmcblk1p1; }"
            )
            rejected = subprocess.run(
                ["sh"], input=runnable, text=True, capture_output=True
            )
            self.assertNotEqual(rejected.returncode, 0)
            self.assertEqual(active.read_text(), "previous working selector")
            corrupt.write_bytes(b"dtb")
            published = subprocess.run(
                ["sh"], input=runnable, text=True, capture_output=True
            )
            self.assertEqual(published.returncode, 0, published.stderr)
            self.assertEqual(active.read_text(), value["extlinux"])
            backup = list((boot / "extlinux").glob("asterinas-backup-*.conf"))
            self.assertEqual(len(backup), 1)
            self.assertEqual(backup[0].read_text(), "previous working selector")
            (root / "1/serial.log").write_text("altered log")
            with self.assertRaisesRegex(
                menu.BootManifestError, "log identity mismatch"
            ):
                menu.promotion_script(value, root)


if __name__ == "__main__":
    unittest.main()
