[Service]
Environment=ASTERINAS_BROWSER_WEB_PROC_DIAGNOSTIC=1
Environment=ASTERINAS_FIREFOX_GECKO_PROFILE=1
Environment=ASTERINAS_BROWSER_WEB_FORMAL_TIMEOUT_SECONDS=300
Environment=MOZ_PROFILER_STARTUP=1
Environment=MOZ_PROFILER_STARTUP_ENTRIES=262144
Environment=MOZ_PROFILER_STARTUP_INTERVAL=10
Environment=MOZ_PROFILER_STARTUP_FEATURES=js,leaf,ipcmessages,processcpu
Environment="MOZ_PROFILER_STARTUP_FILTERS=GeckoMain,DOM Worker,Compositor,Renderer,Socket Thread,SwComposite,MediaDecoderStateMachine"
