# SPDX-License-Identifier: MPL-2.0
[*]
wallpaper_mode=stretch
wallpaper_common=1
wallpaper=/usr/share/asterinas/desktop-wallpaper.svg
desktop_bg=#071426
desktop_fg=#f3fffd
desktop_shadow=#10243a
show_wm_menu=0
sort=name;ascending;
show_documents=0
show_trash=1
show_mounts=1
