// SPDX-License-Identifier: MPL-2.0

use core::time::Duration;

use int_to_c_enum::TryFromInt;
use ostd::mm::VmIo;

use super::SyscallReturn;
use crate::{
    prelude::*,
    process::{pid_table, posix_thread::AsPosixThread},
    time::{
        clockid_t,
        clocks::{
            BootTimeClock, MonotonicClock, MonotonicCoarseClock, MonotonicRawClock, RealTimeClock,
            RealTimeCoarseClock,
        },
        timespec_t,
    },
};

pub fn sys_clock_gettime(
    clockid: clockid_t,
    timespec_addr: Vaddr,
    ctx: &Context,
) -> Result<SyscallReturn> {
    debug!("clockid = {:?}", clockid);

    let timespec = read_clock_timespec(clockid, ctx)?;
    ctx.user_space().write_val(timespec_addr, &timespec)?;

    Ok(SyscallReturn::Return(0))
}

fn read_clock_timespec(clockid: clockid_t, ctx: &Context) -> Result<timespec_t> {
    if clockid < 0 {
        return Ok(timespec_t::from(read_clock(clockid, ctx)?));
    }

    let clock_id = ClockId::try_from(clockid)?;
    let (base, boot_time) = match clock_id {
        ClockId::CLOCK_MONOTONIC => (MonotonicClock::get().read_time(), false),
        ClockId::CLOCK_MONOTONIC_RAW => (MonotonicRawClock::get().read_time(), false),
        ClockId::CLOCK_MONOTONIC_COARSE => (MonotonicCoarseClock::get().read_time(), false),
        ClockId::CLOCK_BOOTTIME => (BootTimeClock::get().read_time(), true),
        _ => return Ok(timespec_t::from(read_clock(clockid, ctx)?)),
    };

    let ns_proxy = ctx.thread_local.borrow_ns_proxy();
    let offset = ns_proxy.unwrap().time_ns().offset_nanos(boot_time);
    let base_ns = i128::from(base.as_secs()) * 1_000_000_000 + i128::from(base.subsec_nanos());
    let total = base_ns.saturating_add(offset);
    Ok(timespec_t {
        sec: total.div_euclid(1_000_000_000) as i64,
        nsec: total.rem_euclid(1_000_000_000) as i64,
    })
}

pub fn sys_clock_getres(
    clockid: clockid_t,
    timespec_addr: Vaddr,
    ctx: &Context,
) -> Result<SyscallReturn> {
    debug!("clockid = {:?}", clockid);

    // Linux validates the clock ID first (EINVAL for invalid clocks), and a
    // NULL timespec pointer is legal: the resolution is simply not copied out.
    let resolution = read_clock_resolution(clockid)?;

    if timespec_addr != 0 {
        let timespec = timespec_t::from(resolution);
        ctx.user_space().write_val(timespec_addr, &timespec)?;
    }

    Ok(SyscallReturn::Return(0))
}

/// Returns the resolution (precision) of the clock specified by `clockid`.
///
/// The coarse clocks (`CLOCK_REALTIME_COARSE`/`CLOCK_MONOTONIC_COARSE`) are
/// updated once per system timer tick (see `ostd::timer::TIMER_FREQ`, 1000 Hz),
/// so their resolution is one tick (1 ms). The remaining supported clocks,
/// including CPU clocks, read a nanosecond-granular clocksource.
fn read_clock_resolution(clockid: clockid_t) -> Result<Duration> {
    if clockid >= 0 {
        let clock_id = ClockId::try_from(clockid)?;
        let resolution = match clock_id {
            ClockId::CLOCK_REALTIME_COARSE | ClockId::CLOCK_MONOTONIC_COARSE => {
                Duration::from_millis(1)
            }
            _ => Duration::from_nanos(1),
        };
        Ok(resolution)
    } else {
        match DynamicClockIdInfo::try_from(clockid)? {
            DynamicClockIdInfo::Pid(_, _) | DynamicClockIdInfo::Tid(_, _) => {
                Ok(Duration::from_nanos(1))
            }
            DynamicClockIdInfo::Fd(_) => return_errno_with_message!(
                Errno::EINVAL,
                "the file descriptor does not provide a dynamic clock"
            ),
        }
    }
}

// The hard-coded clock IDs.
#[expect(non_camel_case_types)]
#[repr(i32)]
#[derive(Clone, Copy, Debug, PartialEq, TryFromInt)]
pub enum ClockId {
    CLOCK_REALTIME = 0,
    CLOCK_MONOTONIC = 1,
    CLOCK_PROCESS_CPUTIME_ID = 2,
    CLOCK_THREAD_CPUTIME_ID = 3,
    CLOCK_MONOTONIC_RAW = 4,
    CLOCK_REALTIME_COARSE = 5,
    CLOCK_MONOTONIC_COARSE = 6,
    CLOCK_BOOTTIME = 7,
}

/// The information decoded from a dynamic clock ID.
///
/// Dynamic clocks are the clocks operates on certain
/// character devices, processes or threads. Their IDs will
/// be generated by encoding the file descriptor, PID or TID.
/// Here we follow the rules in Linux:
///
/// The dynamic clock ID is a 32 bit integer.
/// - The most significant 29 bits hold either a PID or a file descriptor.
/// - Bit 2 indicates whether a cpu clock refers to a thread or a process.
/// - Bits 1 and 0 give the type: PROF=0, VIRT=1, SCHED=2, or FD=3.
/// - A clock ID is invalid if bits 2, 1, and 0 are all set.
///
/// Ref: <https://github.com/torvalds/linux/blob/master/include/linux/posix-timers_types.h>.
#[derive(Debug, PartialEq)]
pub(super) enum DynamicClockIdInfo {
    Pid(u32, DynamicCpuClockType),
    Tid(u32, DynamicCpuClockType),
    #[cfg_attr(all(target_arch = "x86_64", not(ktest)), expect(dead_code))]
    Fd(u32),
}

impl TryFrom<clockid_t> for DynamicClockIdInfo {
    type Error = Error;

    fn try_from(value: clockid_t) -> core::prelude::v1::Result<Self, Self::Error> {
        const CPU_CLOCK_TYPE_MASK: i32 = 0b11;
        const ID_TYPE_MASK: i32 = 0b100;
        const INVALID_MASK: i32 = CPU_CLOCK_TYPE_MASK | ID_TYPE_MASK;

        if (value & INVALID_MASK) == INVALID_MASK {
            return_errno_with_message!(Errno::EINVAL, "invalid clock ID");
        }

        let id = !(value >> 3);
        let raw_clock_type = CPU_CLOCK_TYPE_MASK & value;

        if raw_clock_type == 3 {
            return Ok(DynamicClockIdInfo::Fd(id as u32));
        }
        let cpu_clock_type = DynamicCpuClockType::try_from(raw_clock_type)?;

        if ID_TYPE_MASK & value > 0 {
            Ok(DynamicClockIdInfo::Tid(id as u32, cpu_clock_type))
        } else {
            Ok(DynamicClockIdInfo::Pid(id as u32, cpu_clock_type))
        }
    }
}

#[repr(i32)]
#[derive(Clone, Copy, Debug, PartialEq, TryFromInt)]
pub(super) enum DynamicCpuClockType {
    Profiling = 0,
    Virtual = 1,
    Scheduling = 2,
}

/// Reads the time of a clock specified by the input clock ID.
///
/// If the clock ID does not support, this function will return `Err`.
pub(super) fn read_clock(clockid: clockid_t, ctx: &Context) -> Result<Duration> {
    if clockid >= 0 {
        let clock_id = ClockId::try_from(clockid)?;
        let apply_time_ns = |duration: Duration, boot_time: bool| {
            let ns_proxy = ctx.thread_local.borrow_ns_proxy();
            ns_proxy
                .unwrap()
                .time_ns()
                .apply_offset(duration, boot_time)
        };
        match clock_id {
            ClockId::CLOCK_REALTIME => Ok(RealTimeClock::get().read_time()),
            ClockId::CLOCK_MONOTONIC => Ok(apply_time_ns(MonotonicClock::get().read_time(), false)),
            ClockId::CLOCK_MONOTONIC_RAW => {
                Ok(apply_time_ns(MonotonicRawClock::get().read_time(), false))
            }
            ClockId::CLOCK_REALTIME_COARSE => Ok(RealTimeCoarseClock::get().read_time()),
            ClockId::CLOCK_MONOTONIC_COARSE => Ok(apply_time_ns(
                MonotonicCoarseClock::get().read_time(),
                false,
            )),
            ClockId::CLOCK_BOOTTIME => Ok(apply_time_ns(BootTimeClock::get().read_time(), true)),
            ClockId::CLOCK_PROCESS_CPUTIME_ID => Ok(ctx.process.prof_clock().read_time()),
            ClockId::CLOCK_THREAD_CPUTIME_ID => Ok(ctx.posix_thread.prof_clock().read_time()),
        }
    } else {
        let dynamic_clockid_info = DynamicClockIdInfo::try_from(clockid)?;
        match dynamic_clockid_info {
            DynamicClockIdInfo::Pid(pid, clock_type) => {
                let process = pid_table::pid_table_mut()
                    .get_process(pid)
                    .ok_or_else(|| Error::with_message(Errno::EINVAL, "invalid clock ID"))?;
                match clock_type {
                    // Asterinas accounts execution time in one combined
                    // user-plus-kernel clock.  Until sub-tick scheduler
                    // accounting is available, this is also the best source
                    // for Linux's CPUCLOCK_SCHED view.
                    DynamicCpuClockType::Profiling | DynamicCpuClockType::Scheduling => {
                        Ok(process.prof_clock().read_time())
                    }
                    DynamicCpuClockType::Virtual => {
                        Ok(process.prof_clock().user_clock().read_time())
                    }
                }
            }
            DynamicClockIdInfo::Tid(tid, clock_type) => {
                let thread = pid_table::pid_table_mut()
                    .get_thread(tid)
                    .ok_or_else(|| Error::with_message(Errno::EINVAL, "invalid clock ID"))?;
                let posix_thread = thread.as_posix_thread().unwrap();
                match clock_type {
                    DynamicCpuClockType::Profiling | DynamicCpuClockType::Scheduling => {
                        Ok(posix_thread.prof_clock().read_time())
                    }
                    DynamicCpuClockType::Virtual => {
                        Ok(posix_thread.prof_clock().user_clock().read_time())
                    }
                }
            }
            DynamicClockIdInfo::Fd(_) => return_errno_with_message!(
                Errno::EINVAL,
                "the file descriptor does not provide a dynamic clock"
            ),
        }
    }
}

#[cfg(ktest)]
mod tests {
    use ostd::prelude::ktest;

    use super::{DynamicClockIdInfo, DynamicCpuClockType, read_clock_resolution};
    use crate::prelude::*;

    fn cpu_clock_id(id: u32, kind: u32, per_thread: bool) -> i32 {
        ((!id << 3) | kind | u32::from(per_thread) * 4) as i32
    }

    #[ktest]
    fn decodes_dynamic_cpu_and_fd_clocks() {
        assert_eq!(
            DynamicClockIdInfo::try_from(cpu_clock_id(42, 2, false)).unwrap(),
            DynamicClockIdInfo::Pid(42, DynamicCpuClockType::Scheduling)
        );
        assert_eq!(
            DynamicClockIdInfo::try_from(cpu_clock_id(17, 1, true)).unwrap(),
            DynamicClockIdInfo::Tid(17, DynamicCpuClockType::Virtual)
        );
        assert_eq!(
            DynamicClockIdInfo::try_from(cpu_clock_id(9, 3, false)).unwrap(),
            DynamicClockIdInfo::Fd(9)
        );
    }

    #[ktest]
    fn rejects_reserved_dynamic_clock_encoding() {
        let error = DynamicClockIdInfo::try_from(-1).unwrap_err();
        assert_eq!(error.error(), Errno::EINVAL);
    }

    #[ktest]
    fn reports_tick_resolution_for_cpu_clocks() {
        assert_eq!(
            read_clock_resolution(super::ClockId::CLOCK_PROCESS_CPUTIME_ID as i32).unwrap(),
            core::time::Duration::from_millis(1)
        );
        assert_eq!(
            read_clock_resolution(cpu_clock_id(42, 2, false)).unwrap(),
            core::time::Duration::from_millis(1)
        );
    }
}
